### ISSUE TITLE
Mohist (or other hybrids) are unsupported

### ISSUE THREAD

**Issue by red0fireus** [e-im/FreedomChat#17]
```
[19:08:27 ERROR]: Could not pass event PlayerJoinEvent to FreedomChat v1.2.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.19.2-43.1.52-universal.jar%23143!/:?] {re:classloading}
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.19.2-43.1.52-universal.jar%23143!/:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge-1.19.2-43.1.52-universal.jar%23143!/:?] {re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[forge-1.19.2-43.1.52-universal.jar%23143!/:?] {re:classloading}
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:224) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:181) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:168) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:78) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.network.Connection.m_129483_(Connection.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading}
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1019) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:944) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:791) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: java.lang.NoSuchFieldError: m
        at ru.bk.oharass.freedomchat.FreedomChat.on(FreedomChat.java:94) ~[?:?] {}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?] {}
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[forge-1.19.2-43.1.52-universal.jar%23143!/:?] {re:classloading}
        ... 15 more
```

Got this error with forge and mohist

**Comment by e-im** [comment]
Mohist is not supported. Without doing a lot of extra work to add support for it, it will not work. I'll leave this open so anyone else who has the issue can see it, but I will not be working on a fix for this.

It is possible that by making other design changes it will be fixed, but I have no intention of adding more code specifically to fix this.

**Comment by Mgazul** [comment]
Mohist-1.19.2 does not support any plugins, please wait patiently for 1.19.3+

**Comment by InsideBSITheSecond** [comment]
@Mgazul
this is still not working with:
Mohist 1.20.1-689
FreedomChat 1.5.0
SignedVelocity 1.2.3 (renaming paper-plugin.yml to plugin.yml in the jar file)

relevant log parts:
```
[00:04:45 ERROR]: Error occurred while enabling FreedomChat v1.5.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'int org.bukkit.UnsafeValues.getProtocolVersion()'
        at ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:15) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[00:04:45 INFO]: [FreedomChat] Disabling FreedomChat v1.5.0
[00:04:45 ERROR]: Error occurred while disabling FreedomChat v1.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/network/ChannelInitializeListenerHolder
        at ru.bk.oharass.freedomchat.FreedomChat.onDisable(FreedomChat.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:349) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:365) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:507) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.network.ChannelInitializeListenerHolder
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 14 more
[00:04:45 INFO]: [SignedVelocity] Enabling SignedVelocity v1.2.3
[00:04:45 ERROR]: Error occurred while enabling SignedVelocity v1.2.3 (Is it up to date?)
java.lang.NoClassDefFoundError: io/papermc/paper/event/player/AsyncChatDecorateEvent
        at io.github._4drian3d.signedvelocity.paper.listener.DecorateChatListener.eventClass(DecorateChatListener.java:47) ~[?:?]
        at io.github._4drian3d.signedvelocity.paper.SignedVelocity.onEnable(SignedVelocity.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:549) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:462) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:997de31d-ddc9a2dad-d2eba2c8-47.1.79]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:848) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23198!/:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.event.player.AsyncChatDecorateEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.2.30-universal.jar%23203!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 13 more
[00:04:45 INFO]: [SignedVelocity] Disabling SignedVelocity v1.2.3
```
