### ISSUE TITLE
Doesn't work with folia properly as of april

### ISSUE THREAD

**Issue by Kichura** [e-im/FreedomChat#27]
When attempting to use latest folia with freedomchat 1.4.2 in it, it will just break as a whole because of a missing class:

```
[ERROR]: Error occurred while enabling FreedomChat v1.4.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/network/chat/IChatBaseComponent
        at ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:25) ~[FreedomChat-1.4.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.19.4.jar:git-Folia-"41c5548"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.IChatBaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
```

**Comment by e-im** [comment]
You need to either use the `-reobf` folia jar or a mojang-mapped version of freedomchat. This is not an issue with freedomchat.
